syntax = "proto3";

package press_simulator;

import "google/protobuf/empty.proto";


option go_package = "Kubernetes2/Aggregator/protobuf/press";

service PressSimService {
    //A server-streaming RPC to feed our press metrics to the client (go aggregator)
    rpc FetchMetrics(google.protobuf.Empty) returns (stream PressMetrics);
    rpc FetchConfig(google.protobuf.Empty) returns (PressConfig);
}

enum PressState {
    PRESS_STATE_UNKNOWN = 0;
    EXTEND = 1;
    HOLD = 2;
    RETRACT = 3;
}

message PressMetrics {
    double position = 1;
    double velocity = 2;
    PressState state = 3;
}

message PressConfig {
    double max_depth = 1;
    double speed = 2;
    uint32 dwell_duration = 3;
 }