syntax = "proto3";

package fatigue_worker;

option go_package = "Kubernetes2/Aggregator/protobuf/fatigue";

// Unary service. We process one data batch, and respond the output of our calculation.
service FatigueService {
    rpc ProcessBatch(PressDataBatch) returns (Fatigue);
}

message PressDataSample {
    double position = 1;
    double velocity = 2;
}

message PressDataBatch {
    repeated PressDataSample samples = 1;
    //As we calculate fatigue based on N and N+1, we need a mechanism to compare the last of batch A to the first of batch B.
    PressDataSample prev_batch_last_sample = 2;
    bool has_prev_sample = 3;
}

message Fatigue {
    double batch_wear = 1;
}